export PYTHONPATH="/home/erepie/deyep/"

python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py
python tests/simulation/signal_plus_noise_2.py